# Generated by Django 3.2.5 on 2023-04-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
